spring:
  application:
    name: Eureka-service
    
server:
  port: 8302
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0